use std::sync::Arc;

use axum::{extract::State, routing::post, Json, Router};
use sqlx::SqlitePool;
use tracing::info;

use crate::error::AppError;
use crate::schemas::strategy::{
    AiOpinion, EventSummary, FinalDecision, StrategyLlmResponse, StrategyRequest, StrategyResponse,
};
use crate::schemas::ApiResponse;
use crate::AppState;

pub fn router() -> Router<Arc<AppState>> {
    Router::new().route("/api/strategy", post(get_strategy))
}

async fn get_strategy(
    State(state): State<Arc<AppState>>,
    Json(req): Json<StrategyRequest>,
) -> Result<Json<ApiResponse<StrategyResponse>>, AppError> {
    // Fetch the event first — 404 if it doesn't exist.
    let event = fetch_event(&state.db, &req.event_id)
        .await?
        .ok_or_else(|| AppError::NotFound("EVENT_NOT_FOUND".to_string()))?;

    // Return cached strategy if already generated by the background task.
    if let Some(cached) = fetch_strategy(&state.db, &req.event_id, &event).await? {
        info!(event_id = %req.event_id, "strategy cache hit");
        return Ok(Json(ApiResponse::ok(cached)));
    }

    // Background task hasn't finished yet (rare edge case — generate synchronously).
    info!(event_id = %req.event_id, "strategy not cached, generating synchronously");
    let product_name = fetch_product_name(&state.db, &event.product_id)
        .await?
        .unwrap_or_else(|| "Unknown Product".to_string());

    let prompt =
        crate::prompts::strategy::build(&product_name, &event.event_type, &event.event_data_str);
    let raw = state
        .llm
        .call_text(&prompt, crate::prompts::strategy::STRATEGY_MODEL)
        .await?;
    let parsed: StrategyLlmResponse = serde_json::from_value(raw)
        .map_err(|e| AppError::LlmError(format!("STRATEGY_PARSE_FAILED: {e}")))?;

    let strategy = persist_strategy(&state.db, &req.event_id, parsed, &event).await?;
    Ok(Json(ApiResponse::ok(strategy)))
}

struct EventRow {
    id: String,
    product_id: String,
    event_type: String,
    event_data_str: String,
    triggered_at: String,
}

async fn fetch_event(pool: &SqlitePool, event_id: &str) -> Result<Option<EventRow>, AppError> {
    let row = sqlx::query_as::<_, (String, String, String, String, String)>(
        "SELECT id, product_id, event_type, event_data, triggered_at \
         FROM market_events WHERE id = ?",
    )
    .bind(event_id)
    .fetch_optional(pool)
    .await?;

    Ok(row.map(
        |(id, product_id, event_type, event_data_str, triggered_at)| EventRow {
            id,
            product_id,
            event_type,
            event_data_str,
            triggered_at,
        },
    ))
}

async fn fetch_strategy(
    pool: &SqlitePool,
    event_id: &str,
    event: &EventRow,
) -> Result<Option<StrategyResponse>, AppError> {
    let row = sqlx::query_as::<
        _,
        (
            String,
            String,
            String,
            String,
            String,
            Option<String>,
            String,
        ),
    >(
        "SELECT id, marketing_ai, product_ai, sales_ai, final_decision, model_used, generated_at \
         FROM strategies WHERE event_id = ?",
    )
    .bind(event_id)
    .fetch_optional(pool)
    .await?;

    if let Some((id, mkt, prd, sls, fin, model, gen_at)) = row {
        let marketing_ai: AiOpinion = serde_json::from_str(&mkt)
            .map_err(|e| AppError::InternalError(format!("marketing_ai deserialize: {e}")))?;
        let product_ai: AiOpinion = serde_json::from_str(&prd)
            .map_err(|e| AppError::InternalError(format!("product_ai deserialize: {e}")))?;
        let sales_ai: AiOpinion = serde_json::from_str(&sls)
            .map_err(|e| AppError::InternalError(format!("sales_ai deserialize: {e}")))?;
        let final_decision: FinalDecision = serde_json::from_str(&fin)
            .map_err(|e| AppError::InternalError(format!("final_decision deserialize: {e}")))?;

        Ok(Some(StrategyResponse {
            id,
            event_id: event_id.to_string(),
            marketing_ai,
            product_ai,
            sales_ai,
            final_decision,
            model_used: model,
            cached: true,
            generated_at: gen_at,
            event: event_to_summary(event),
        }))
    } else {
        Ok(None)
    }
}

async fn persist_strategy(
    pool: &SqlitePool,
    event_id: &str,
    parsed: StrategyLlmResponse,
    event: &EventRow,
) -> Result<StrategyResponse, AppError> {
    let id = uuid::Uuid::new_v4().to_string();
    let generated_at = chrono::Utc::now().to_rfc3339();
    let model = crate::prompts::strategy::STRATEGY_MODEL;

    sqlx::query(
        "INSERT OR IGNORE INTO strategies \
         (id, event_id, marketing_ai, product_ai, sales_ai, final_decision, model_used, generated_at) \
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
    )
    .bind(&id)
    .bind(event_id)
    .bind(serde_json::to_string(&parsed.marketing_ai).unwrap_or_default())
    .bind(serde_json::to_string(&parsed.product_ai).unwrap_or_default())
    .bind(serde_json::to_string(&parsed.sales_ai).unwrap_or_default())
    .bind(serde_json::to_string(&parsed.final_decision).unwrap_or_default())
    .bind(model)
    .bind(&generated_at)
    .execute(pool)
    .await?;

    Ok(StrategyResponse {
        id,
        event_id: event_id.to_string(),
        marketing_ai: parsed.marketing_ai,
        product_ai: parsed.product_ai,
        sales_ai: parsed.sales_ai,
        final_decision: parsed.final_decision,
        model_used: Some(model.to_string()),
        cached: false,
        generated_at,
        event: event_to_summary(event),
    })
}

fn event_to_summary(event: &EventRow) -> EventSummary {
    EventSummary {
        id: event.id.clone(),
        product_id: event.product_id.clone(),
        event_type: event.event_type.clone(),
        event_data: serde_json::from_str(&event.event_data_str).unwrap_or(serde_json::json!({})),
        triggered_at: event.triggered_at.clone(),
    }
}

async fn fetch_product_name(
    pool: &SqlitePool,
    product_id: &str,
) -> Result<Option<String>, AppError> {
    let row = sqlx::query_as::<_, (String,)>("SELECT name FROM products WHERE id = ?")
        .bind(product_id)
        .fetch_optional(pool)
        .await?;
    Ok(row.map(|(name,)| name))
}
